name: Deploy to SIT

on:
  push:
    branches:
      - sit

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Authenticate with Salesforce Org
        run: |
          echo ${{ secrets.SF_AUTH_URL_SIT }} > ./authURL
          sf org login sfdx-url -f ./authURL --set-default --json

      - name: Deploy metadata to SIT
        run: |
          sf project deploy start --manifest manifest/package.xml --target-org sit --wait 10

      - name: Run Apex Tests
        run: |
          sf apex run test --target-org sit --wait 10
